// Optimize the wide brand banner for the web. Source lives in ../ (the fifa.archv working
// folder), so this is a hand-run tool and NOT part of `npm run build`: nothing outside this
// repo may be read at build time (see trap 0 in CLAUDE.md).
//
// This used to also build logo-badge.png and logo-badge@192.png by circle-cropping
// THEARCHV_LOGO.png. Both are now crest-derived and generated by scripts/build-crest.mjs from
// the committed monogram SVG, along with every other crest asset the site serves. Running that
// old badge step today would clobber them with the retired navy mark, so it is gone rather than
// left commented out. Rebuild the marks with `npm run crest`.
import sharp from 'sharp';
import { existsSync } from 'node:fs';
import { mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC = join(__dirname, '..', '..');
const OUT = join(__dirname, '..', 'public', 'brand');
if (!existsSync(join(SRC, 'ARCHV_BANNER.png'))) {
  console.error(`[brand-assets] ARCHV_BANNER.png not found under ${SRC} — this script reads outside the repo and only runs in the founder's workspace; never add it to the build chain.`);
  process.exit(1);
}
await mkdir(OUT, { recursive: true });

// --- Banner: the wide "The ARCHV" banner, web-optimized ---
await sharp(join(SRC, 'ARCHV_BANNER.png')).resize({ width: 2000 }).webp({ quality: 74 }).toFile(join(OUT, 'banner.webp'));
await sharp(join(SRC, 'ARCHV_BANNER.png')).resize({ width: 1100 }).webp({ quality: 72 }).toFile(join(OUT, 'banner-sm.webp'));
console.log('✓ banner.webp + banner-sm.webp');
